Examen 3/CG_Operadores/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('Operadores.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

Examen 3/Operadores/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from . import vistas_scanner
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

app_name = 'Ops'

urlpatterns = [
    path('', views.index, name='index'),
    path('loginfirebase', views.login, name='login'),
    path('indexlogin', views.indexlogin, name='indexlogin'),
    path('mod_scanner/', vistas_scanner.index_vista, name='scanner_index'),
    path('contactanos/', vistas_scanner.contactanos, name='contactanos'),
    path('contactanos/send_message/', vistas_scanner.message_send),
    path('mod_scanner/<str:name>', vistas_scanner.operators_2, name='scanner_intro'),
    path('mod_scanner/<str:name>/corners', vistas_scanner.get_corners),
    path('mod_scanner/<str:name>/scanner', vistas_scanner.make_scanner),
    path('img/<str:name>', views.operators, name='operators'),
    path('img/<str:name>/data_thresholding', views.image_thresholding),
    path('img/<str:name>/data_contrast', views.image_contrast_streching),
    path('img/<str:name>/data_equalization', views.image_histogram_equalization),
    path('img/<str:name>/data_exponential', views.image_exponential),
    path('img/<str:name>/data_logarithm', views.image_logarithm),
    path('img/<str:name>/data_square', views.image_square_root),
    path('img/<str:name>/data_pow', views.image_raise_power),
    path('img/<str:name>/data_addition', views.image_addition),
    path('img/<str:name>/data_difference', views.image_difference),
    path('img/<str:name>/data_dot', views.image_dot),
    path('img/<str:name>/data_division', views.image_division),
    path('img/<str:name>/data_blending', views.image_blending),
    path('img/<str:name>/data_AND', views.image_AND),
    path('img/<str:name>/data_OR', views.image_OR),
    path('img/<str:name>/data_XOR', views.image_XOR),
    path('img/<str:name>/up_image', views.up_image),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Examen 3/Operadores/models.py
from django.db import models

# Create your models here.

Examen 3/Operadores/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.urls import reverse
from .utils import *
# Create your views here.


def index(request):
    if request.method == 'POST':
        my_file = request.FILES['Original']
        archivo = (os.path.splitext(my_file.name))
        nombre = archivo[0]
        ubication_image = MEDIA_ROOT + "/"+nombre
        if os.path.isdir(ubication_image):
            shutil.rmtree(ubication_image)
        os.mkdir(ubication_image)
        fs = FileSystemStorage(location=ubication_image)
        filename = fs.save(my_file.name, my_file)
        return redirect(reverse('Ops:operators', kwargs={'name': nombre}))
    return render(request, 'Pages/index.html')


def login(request):
    return render(request, 'Pages/loginfirebase.html')

def indexlogin(request):
    return render(request, 'Index.html')

def image_exponential(request, name):
    if request.method == 'POST':
        path = request.POST['camino']
        values = request.POST['nombre']
        constante = float(request.POST['constante'])
        constante1 = float(request.POST['constante1'])
        estado, name_image, npath = solve_exponential(path, values, constante, constante1)
        if estado:
            return JsonResponse({
                'Estado': "OK",
                'nombre': name_image,
                'camino': npath,
                'imagen': "/media/" + name_image + "/" + name_image
            })
        else:
            return JsonResponse({'State': 'fail'})
    else:
        return JsonResponse({'State': 'fail'})


def image_logarithm(request, name):
    if request.method == 'POST':
        path = request.POST['camino']
        values = request.POST['nombre']
        constante = float(request.POST['constante'])
        estado, name_image, npath = solve_logarithm(path, values, constante)
        if estado:
            return JsonResponse({
                'Estado': "OK",
                'nombre': name_image,
                'camino': npath,
                'imagen': "/media/" + name_image + "/" + name_image
            })
        else:
            return JsonResponse({'State': 'fail'})
    else:
        return JsonResponse({'State': 'fail'})


def image_raise_power(request, name):
    if request.method == 'POST':
        path = request.POST['camino']
        values = request.POST['nombre']
        constante = float(request.POST['constante'])
        constante1 = float(request.POST['constante1'])
        estado, name_image, npath = solve_raise_power(path, values, constante, constante1)
        if estado:
            return JsonResponse({
                'Estado': "OK",
                'nombre': name_image,
                'camino': npath,
                'imagen': "/media/" + name_image + "/" + name_image
            })
        else:
            return JsonResponse({'State': 'fail'})
    else:
        return JsonResponse({'State': 'fail'})


def image_addition(request, name):
    if request.method == 'POST':
        path = request.POST['camino']
        values = request.POST['nombre']
        constante = request.POST['constante']
        constante2 = request.FILES.get('image', False)
        checker = request.POST['op_aritmeticas']
        if checker == "1":
            constante = float(constante)
        else:
            constante = up_image(constante2, name)

        estado, name_image, npath = solve_addition(path, values, constante)
        if estado:
            return JsonResponse({
                'Estado': "OK",
                'nombre': name_image,
                'camino': npath,
                'imagen': "/media/" + name_image + "/" + name_image
            })
        else:
            return JsonResponse({'State': 'fail'})
    else:
        return JsonResponse({'State': 'fail'})


def image_difference(request, name):
    if request.method == 'POST':
        path = request.POST['camino']
        values = request.POST['nombre']
        constante = request.POST['constante']
        constante2 = request.FILES.get('image', False)
        checker = request.POST['op_aritmeticas']
        if checker == "1":
            constante = float(constante)
        else:
            constante = up_image(constante2, name)
        estado, name_image, npath = solve_difference(path, values, constante)
        if estado:
            return JsonResponse({
                'Estado': "OK",
                'nombre': name_image,
                'camino': npath,
                'imagen': "/media/" + name_image + "/" + name_image
            })
        else:
            return JsonResponse({'State': 'fail'})
    else:
        return JsonResponse({'State': 'fail'})


def image_dot(request, name):
    if request.method == 'POST':
        path = request.POST['camino']
        values = request.POST['nombre']
        constante = request.POST['constante']
        constante2 = request.FILES.get('image', False)
        checker = request.POST['op_aritmeticas']
        if checker == "1":
            constante = float(constante)
        else:
            constante = up_image(constante2, name)
        estado, name_image, npath = solve_dot(path, values, constante)
        if estado:
            return JsonResponse({
                'Estado': "OK",
                'nombre': name_image,
                'camino': npath,
                'imagen': "/media/" + name_image + "/" + name_image
            })
        else:
            return JsonResponse({'State': 'fail'})
    else:
        return JsonResponse({'State': 'fail'})


def image_division(request, name):
    if request.method == 'POST':
        path = request.POST['camino']
        values = request.POST['nombre']
        constante = request.POST['constante']
        constante2 = request.FILES.get('image', False)
        checker = request.POST['op_aritmeticas']
        if checker == "1":
            constante = float(constante)
        else:
            constante = up_image(constante2, name)
        estado, name_image, npath = solve_division(path, values, constante)
        if estado:
            return JsonResponse({
                'Estado': "OK",
                'nombre': name_image,
                'camino': npath,
                'imagen': "/media/" + name_image + "/" + name_image
            })
        else:
            return JsonResponse({'State': 'fail'})
    else:
        return JsonResponse({'State': 'fail'})


def image_blending(request, name):
    if request.method == 'POST':
        path = request.POST['camino']
        values = request.POST['nombre']
        constante = request.POST['constante']
        constante2 = request.FILES.get('image', False)
        constante2 = up_image(constante2, name)
        estado, name_image, npath = solve_blinding(path, values, constante2, constante)
        if estado:
            return JsonResponse({
                'Estado': "OK",
                'nombre': name_image,
                'camino': npath,
                'imagen': "/media/" + name_image + "/" + name_image
            })
        else:
            return JsonResponse({'State': 'fail'})
    else:
        return JsonResponse({'State': 'fail'})


def image_AND(request, name):
    if request.method == 'POST':
        path = request.POST['camino']
        values = request.POST['nombre']
        constante2 = request.FILES.get('image', False)
        another_image = up_image(constante2, name)
        estado, name_image, npath = solve_and(path, values, another_image)
        if estado:
            return JsonResponse({
                'Estado': "OK",
                'nombre': name_image,
                'camino': npath,
                'imagen': "/media/" + name_image + "/" + name_image
            })
        else:
            return JsonResponse({'State': 'fail'})
    else:
        return JsonResponse({'State': 'fail'})


def image_OR(request, name):
    if request.method == 'POST':
        path = request.POST['camino']
        values = request.POST['nombre']
        constante2 = request.FILES.get('image', False)
        another_image = up_image(constante2, name)
        estado, name_image, npath = solve_or(path, values, another_image)
        if estado:
            return JsonResponse({
                'Estado': "OK",
                'nombre': name_image,
                'camino': npath,
                'imagen': "/media/" + name_image + "/" + name_image
            })
        else:
            return JsonResponse({'State': 'fail'})
    else:
        return JsonResponse({'State': 'fail'})


def image_XOR(request, name):
    if request.method == 'POST':
        path = request.POST['camino']
        values = request.POST['nombre']
        constante2 = request.FILES.get('image', False)
        another_image = up_image(constante2, name)
        estado, name_image, npath = solve_xor(path, values, another_image)
        if estado:
            return JsonResponse({
                'Estado': "OK",
                'nombre': name_image,
                'camino': npath,
                'imagen': "/media/" + name_image + "/" + name_image
            })
        else:
            return JsonResponse({'State': 'fail'})
    else:
        return JsonResponse({'State': 'fail'})


def image_contrast_streching(request, name):
    if request.method == 'POST':
        path = request.POST['camino']
        values = request.POST['nombre']
        constante = float(request.POST['constante'])
        constante1 = float(request.POST['constante1'])
        estado, name_image, npath = solve_contrast_streching(path, values, constante, constante1)
        if estado:
            return JsonResponse({
                'Estado': "OK",
                'nombre': name_image,
                'camino': npath,
                'imagen': "/media/" + name_image + "/" + name_image
            })
        else:
            return JsonResponse({'State': 'fail'})
    else:
        return JsonResponse({'State': 'fail'})


def image_square_root(request, name):

Examen 3/Operadores/templates/Pages/Image_Visualization.html
{% extends "../base.html" %}
{% load static %}

{% block centro %}

<div class="cuerpo">
    <div class="container">
        <div class="cuerpo-text">
            <br><br><br><br><br><br>

            <div class="container text-center h-100 d-flex justify-content-center align-items-center">
                <div class="container">
                    <form method="POST" id="Change_Image" enctype="multipart/form-data">
                        {% csrf_token %}
                        <h2 class="cuerpo-heading" > Imagen_Original </h2>
                        <img src="{{ imagen }}"  id = "ori_img" class="img-thumbnail">
                        <br>
                        <input type="hidden" id="camino" name="camino" value="{{camino}}" >
                        <input type="hidden" id="nombre" name="nombre" value="{{nombre}}" >
                        <br>
                        <div class="col-xs-3">
                        <select name="algoritmo" id="algoritmo" class="form-control">
                            <option value="''"> Selecione un Operador </option>
                            <option value=1>Thresholding</option>
                            <option value=2>Contrast stretching</option>
                            <option value=3>Ecualización de histograma</option>
                            <option value=4>Operador logaritmico</option>
                            <option value=5>Operador raiz</option>
                            <option value=6>Operador exponencial</option>
                            <option value=7>Operador raise to power</option>
                            <option value=8>Sumar</option>
                            <option value=9>Restar</option>
                            <option value=10>Multiplicar</option>
                            <option value=11>Dividir</option>
                            <option value=12>Blending</option>
                            <option value=13>AND</option>
                            <option value=14>OR</option>
                            <option value=15>XOR</option>
                        </select>
                        <br>
                        <div id = "aritmetica">
                            <select name="op_aritmeticas" id="op_aritmeticas" class="form-control">
                                <option value=1>Con constante</option>
                                <option value=2>Con imagenes</option>
                            </select>
                        </div>

                        <br>
                        <div id ='bot'>
                            <div class="form-group" id="const1">
                                <label for="constante">Constante1: </label>
                                <input type="number" step="0.01" id="constante" name="constante">
                            </div>
                            <div class="form-group" id="const2">
                                 <label for="constante1">Constante2: </label>
                                <input type="number" step="0.01" id="constante1" name="constante1">
                            </div>
                            <div class="form-group" id="const3">
                                <label for="constante2">Constante3: </label>
                                <input type="number" step="0.01" id="constante2" name="constante2">
                            </div>
                            <div class="form-group" id="const4">
                                 <label for="constante3">Constante4: </label>
                                <input type="number" step="0.01" id="constante3" name="constante3">
                            </div>
                            <div class="form-group" id="const5">
                                <label for="file">Otra Imagen: </label>
                                <input type="file" id="file" name="image">
                                <img id="image">
                            </div>
                        </div>
                        <button type="submit" class="btn btn-warning text-dark btn-banner"> Utilizar</button>
                    </div>
                </form>
                </div>
                <br>
                <div id="resul" class="container">
                    <h2 id="enun" class="cuerpo-heading"> Imagen_Modificada con Operador Exponencial </h2>
                    <img src="" id="img_exp" name="img_exp" class="img-thumbnail">
                    <input type="hidden" value="No hay Data, fallo" id="Check" name="Check">
                    <br>
                    <button onclick="usa_este()" class="btn btn-warning text-dark btn-banner">Seleccionar esta imagen</button>
                    <button onclick="downlod()" class="btn btn-primary text-dark btn-banner">Descargar</button>
                    
                    <!-- Facebook logout-->
                </div>

            </div>
            <br><br>
    <!--
    <div class="container center">
        <form action="{% url 'Ops:index' %}">
            <button class="btn btn-primary">Regresar</button>
        </form>

    </div>
    -->
        </div>
    </div>
</div>
{% endblock centro %}


{% block codes_js %}
<script src="{% static 'js/funciones.js' %}"></script>
<script src="{% static 'js/tokens.js' %}"></script>
<script src="{% static 'js/check_aritmetica.js' %}"></script>
<script>

    const $form = document.querySelector('#Change_Image');

    const $image = document.querySelector('#image');
    const $file = document.querySelector('#file');
    function renderImage(formData) {
      const file = formData.get('image');
      const image = URL.createObjectURL(file);
      $image.setAttribute('src', image);
    }

    $file.addEventListener('change', (event) => {
      const formData = new FormData($form);
      renderImage(formData);
    })

</script>
<script>

    function usa_este(){
     var direccion = new String(document.getElementById('img_exp').src);
     console.log(direccion);
     document.getElementById('ori_img').src=direccion;
     document.getElementById('nombre').value = nnombre;
     document.getElementById('camino').value = ncamino;
     console.log($(nombre).val());
     console.log($(camino).val());
    }
</script>




<script>
        var nnombre;
        var ncamino;

        $("#Change_Image").submit(function (e) {
            console.log($(nombre).val());
            console.log($(camino).val());
            e.preventDefault();
            var serializedData = new FormData(this); // $(this).serializeObject();
            var variable1 = $(nombre).val();
            var variable2= $(algoritmo).val();
            var url_to_send = get_url_to_send(variable1,variable2);
            $.ajax({
                type: 'POST',
                url: url_to_send,
                data: serializedData,
                processData: false,
                contentType: false,
                success: function (response) {
                    if(response.Estado == "OK"){
                        document.getElementById('img_exp').src=response.imagen;
                        nnombre = response.nombre;
                        ncamino = response.camino;
                    }
                },
                error: function (response) {
                    // alert the error if any error occured
                   $(Check).attr("type","readonly");
                   console.log(response);
                }
            })
        })
</script>
<script>
    var upload = new FileUploadWithPreview('myUniqueUploadId')
</script>
<!-- Facebook logout-->

</script>
{% endblock codes_js %}

Examen 3/Operadores/templates/Pages/cabecera.html
{% load static %}
{% load socialaccount %}
{% providers_media_js %}

<div class="banner">
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" id="banner">
      <div class="container">
    <!-- Brand -->
    <a class="navbar-brand" href="#"><span>Computación </span> Gráfica</a>

    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Navbar links -->
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'Ops:index' %}">Página Inicio</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'Ops:contactanos' %}">Contactanos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'Ops:index' %}">Regresar</a>
        </li>
        <!--li class="nav-item">
          <a class="nav-link" href="{% url 'Ops:indexlogin' %}">Login</a>
        </li-->
         <!-- Dropdown -->
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">

        </a>
        <div class="dropdown-menu">
        </div>
      </li>
      </ul>
    </div>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
      </div>
       <!--
      <div>
        <a class="btn btn-primary" href="{% url 'Ops:scanner_index' %}">Acceder como usuario libre</a>

        {%if user.is_authenticated%}
                <p>Bienvenido! <b> {{user.username}} </b></p>
        {%else%}
                <a href="{% provider_login_url 'google' %}" class="btn btn btn-danger btn-lg btn-block" role="button" aria-pressed="true">Iniciar con Google</a>
        {%endif%}

      </div>
      -->
  </nav>
</div>

Examen 3/Operadores/templates/Pages/footer.html
<!--
<section id="about">
<div class="container">
	<div class="text-intro">
	<h2>Acerca de Nosotros</h2>
		<p>Descripcion que no tengo idea</p>
	</div>
</div>
</section>
-->

Examen 3/Operadores/templates/Pages/index.html
{% extends "../base.html" %}

{% block centro %}
<script src="https://apis.google.com/js/platform.js" async defer></script>

<div class="banner">
	<div class="container">
	    <div class="banner-text">
	        <div class="banner-heading">
                Scan online
	        </div>
	        <div class="banner-sub-heading">
                Escanea tus documentos desde una foto
	        </div>

            <div class="container text-center h-100 d-flex justify-content-center align-items-center">
                <form method = "post" enctype="multipart/form-data" >
                        {% csrf_token %}
                        
                        <div class="row justify-content-around">
                                <input type="file" id="Original" name="Original" class="btn btn-warning text-dark btn-banner" >
                                &nbsp;
                                &nbsp;
                                <button type="submit" class="btn btn-warning text-dark btn-banner" >Cargar</button>
                        </div>
                        <br>
                </form>
            </div>
	    </div>
	</div>

</div>


{% endblock centro %}

Examen 3/Operadores/templates/Pages/loginfirebase.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Base de datos Firebase</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/estilos.css' %}">
  <meta charset="utf-8">
</head>
<body>
<header id="cabecera">Inicio de Sesión
</header>
<section>
	<center>
    <br>
		<label>Usuario</label>
    <br>
    <input id="user" type="text" placeholder="Usuario">
		<br>
    <br>
		<label>Contraseña</label>
    <br>
    <input id="password" type="password" placeholder="Constraseña">
    <br>
    <br>
    <button id="register" onclick="signIn()">Iniciar sesión</button>
  </center>
</section>
<script src="https://www.gstatic.com/firebasejs/8.2.5/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.2.5/firebase-auth.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.2.5/firebase-database.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.2.5/firebase-analytics.js"></script>
<center>
</center>
<script id="MainScript">
	 // Your web app's Firebase configuration
  // For Firebase JS SDK v7.20.0 and later, measurementId is optional
  	var firebaseConfig = {
		    apiKey: "AIzaSyBF66jpmKx3C_YCyYBUwozoLFH9HLk0Ouc",
		    authDomain: "mysite-7a120.firebaseapp.com",
		    databaseURL: "https://mysite-7a120-default-rtdb.firebaseio.com",
		    projectId: "mysite-7a120",
		    storageBucket: "mysite-7a120.appspot.com",
		    messagingSenderId: "752547508653",
		    appId: "1:752547508653:web:1f64eb4ce12343378af124"
  	};
  // Initialize Firebase
  firebase.initializeApp(firebaseConfig);
  firebase.analytics();
 //Firebase auth
 const auth = firebase.auth();
  
  
  
  function signIn(){
    
    var email = document.getElementById("user");
    var password = document.getElementById("password");
    
    const promise = auth.signInWithEmailAndPassword(email.value, password.value);
    typeof(promise);
    promise.catch(e => alert(e.message));
    alert("Bienvenido");
    window.location.href = "{% url 'Ops:scanner_index' %}";
  
}
 
</script>
</body>
</html>